### ISSUE TITLE
Barcodes

### ISSUE THREAD

**Issue by asamedy** [waldronlab/MultiAssayExperimentData#4]
Trying to use TCGAutils to chop barcodes down  but still having some issues.

Also Pdat should have real names but don't.

**Comment by LiNk-NY** [comment]
Hey Andy, @asamedy
What issues are you having?
Can you post some reproducible example code?
Thanks,
Marcel

**Comment by asamedy** [comment]
Hey Marcel,
I'll send it to you when I get back to my computer. Thanks!!

On Jun 28, 2017 10:58 AM, "Marcel Ramos" <notifications@github.com> wrote:

Hey Andy, @asamedy <https://github.com/asamedy>
What issues are you having?
Can you post some reproducible example code?
Thanks,
Marcel

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/waldronlab/MultiAssayExperimentData/issues/4#issuecomment-311685932>,
or mute the thread

**Comment by asamedy** [comment]
library(multiassayexperiment)
library(multiassayexperimentdata)
library(TCGAutils)


mae <- importcBioPortal("/Users/AndySamedy/Downloads/uvm_tcga.tar.gz")

.generateMap(colData, experiments, TCGAutils::TCGAbarcode) is what i changed in multiassayexperiment

[uvm_tcga.tar.gz]
(https://github.com/waldronlab/MultiAssayExperimentData/files/1112411/uvm_tcga.tar.gz)

**Comment by LiNk-NY** [comment]
Hi Andy, @asamedy

From what I can tell from the code, you have to generate the sample map using the helper function (`generateMap`) in the `TCGAutils` package first and then call the `MultiAssayExperiment` constructor function with the `sampleMap` already created. Otherwise, the `MultiAssayExperiment` constructor function will assume that `colData` rows are the same as in the experiment colnames and they are not thus returning an error.

Regards,
Marcel
